name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./portal

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          DIRECTUS_URL: http://placeholder

      - name: Run tests
        run: yarn test